from mysql.connector import Error
import mysql.connector




try:
	connection = mysql.connector.connect(
			host = "localhost",
			port = 3306,
			user = "root",
			password = "",
			database = "python_inserciones_masivas"
		)

	if connection.is_connected():
		print("Conexi贸n establecida")
	else:
		print("No se pudo establecer la conexi贸n")
except Error as ex:
	print(f"Error durante la conexi贸n{ex}")
else:
	pass
finally:
    if connection.is_connected():
        connection.close()
        print("Conexi贸n cerrada")

        